### ISSUE TITLE
HS220/HS105 Issues

### ISSUE THREAD

**Issue by wtowbin** [DaveGut/TP-Link-SmartThings#12]
I have a Smarthings hub, 1 HS220 and  4 HS105s. KASA application has been installed and is working correctly on my Samsung 8 (and IPAD). Following Dave's instructions I have installed TP-Link Smartthings Manager in my SmartApps (IDE) (no device handlers are installed). 
The TP-Link Smarthings Manager is also installed on Samsung and shows in Smartthings under Automation SmartApps. 
when I select TP-Link Smarthings Manager and then Kasa Device installer Page, I can Select Devices to Add (says 5 are found). When I select there devices and Save, eventually message pops up saying "successful added TP-Link Manager" (or something similar). 
Unfortunately, the added devices are nowhere to be found ! not on any page of Smartthings app or on IDE panels. If I go back to Device Installer Page, I see devices unchecked. 

What am I doing wrong ?

Pls help, Walter

**Comment by DaveGut** [comment]
Handled via the SmartThings blog.
