### ISSUE TITLE
Trouble Installing New Dimmers 

### ISSUE THREAD

**Issue by sunnyghai** [DaveGut/TP-Link-SmartThings#13]
Dave, I tried to add new HS220 dimmers today and the old smart app is not working.  I updated to the new smart app but am not getting any love.  

I have 34 existing devices.  Do I need to delete and reinstall them all?  If so, do I need a new DH for them? If so, where are they?  I only see a new service manager that was updated 8 days ago as of today.  Thanks in advance.

**Comment by sunnyghai** [comment]
Dave, I updated the new DH and App, but my old devices do not work.  Just the two new ones.  Will I need to reinstall those?

**Comment by DaveGut** [comment]
Sunny,

Did you follow the update instructions?  You will need to select and save preferences on the devices as you upgrade to the new system. 

Dave

**Comment by sunnyghai** [comment]
Hi Dave,

I ended up deleting and reinstalling all the devices using the latest handler and apps.  I am noticing a couple of problems:

1) In the Smart App, when I go to the Device Preferences Page, select a device, press done, and press save, I get "an unexpected error occured." It doesn't matter if I just update one device at a time, or do all 36 devices at a time.  My devices consist of HS220, HS 100, HS105 & HS200.
2) Physical state changes (pressing my devices on/off) do not get updated on the SmartThings App.

Any help would be appreciated.

Sunny

**Comment by DaveGut** [comment]
Make sure you have both device handles installed.  Turn on logging and get logs.

You are probably missing the switch h dh.




Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by sunnyghai** [comment]
![screen shot 2019-02-17 at 5 56 33 pm](https://user-images.githubusercontent.com/31091096/52920690-7c889d80-32dd-11e9-9575-729d6fbf51d9.png)
I have these four DH installed.  Am I missing anything?

**Comment by DaveGut** [comment]
I need the logs.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by sunnyghai** [comment]
Dave,

I am still a bit new to this.  What do you want the logs of? I am testing a HS105 (only because I move it to computer for testing).  In live logging, I can see it turn on/off when I turn on/off in the ST app.  However, it does nothing if I physically turn it on/off or make the changes in the Kasa App.  

Sunny

**Comment by DaveGut** [comment]
Since it is failing on install, run the log during the installation process to record the failure details.  I may have to create an error ignore function in the Smart Ap.

**Comment by sunnyghai** [comment]
I got the devices to install, but did get an error on the preferences page: "6:25:51 PM: error java.lang.NullPointerException: Cannot get property 'value' on null object @line 898 (doCall)"

**Comment by DaveGut** [comment]
For now, do not use the Preferences in the Smart App.  Set preferences using the device setting page in the classic phone app.  There is a problem in the Smart App in the preferences section.  I will update the smart app to fix this code.

**Comment by sunnyghai** [comment]
Understood.  I still have a problem with the device states not being updated if I turn the device on/off in the Kasa app or make a physical change.  Not sure how to get the logs to you as there are no errors in the logs.  The changes in states don't show up in live logs.

**Comment by DaveGut** [comment]
Sunny,

There is a persistent problem in the phone app of the state not being updated.  You can verify the state has changed by going to the details page (with all of the tiles) and then back to the device list.  If the new state is correct, it is working as expected.  THERE IS NOTHING I CAN DO ABOUT THIS.

The device handler is designed to automatically update the state after the command is sent to the device.  It typically works great; however, again, if the server is busy the state updates to the phone app take a low priority.  One of the reasons I am abandoning Smart Things.

Regards,

Dave

**Comment by sunnyghai** [comment]
Dave,

I hope you don’t abandon SmartThings for some selfish reasons: I have a lot of TP-Link devices invested in my home and everything seemed to be working well before the last update.

I tried removing two devices (an HS100 aka Coffee Maker and an HS105 aka Roomba).  They were installed on 7:19:31 and 7:19:32.  This was just before the trace info.  I don't know if this will help.

BTW, I am using the classic app, I don’t see any detail page with tiles.

Thanks,
Sunny
![screen shot 2019-02-17 at 7 27 10 pm](https://user-images.githubusercontent.com/31091096/52921940-5e756a00-32ea-11e9-9acc-745c051d464f.png)

**Comment by DaveGut** [comment]
The detail page I am discussing is on the My Home tab, Things.  I that tab, there is a line for each device.  Select the device, you will get to a device detail page.  In the upper right corner, the gear icon will take you to the preferences page.  There you can update preferences or delete the device.

**Comment by sunnyghai** [comment]
Dave,

Got it. I use this page to remove devices.  I noticed that there is no information for Device Refresh Rate, Device IP (Hub Only…) or Device Gateway.  Do I need to update this information to have the app work properly?  I never saw this required information in your older apps.

Thanks,
Sunny

**Comment by DaveGut** [comment]
No.  Preference selection is purely optional and for only some parameters.  Again, do not use that page in the app right now.  I am updating and will fix several issues and concerns.  I should have it out in several days and it will NOT require other updates.

**Comment by sunnyghai** [comment]
OK, I'll wait for the new update.  Thanks again for all your help!

**Comment by sunnyghai** [comment]
Dave,

I did some testing and it looks like the ST app will eventually update the status of a TPLInk device, but it takes about 20 seconds. The older apps/DH recognized the changes much faster.  I only noticed the difference now, because I was writing/testing some Pistons in WebCoRE and was looking at the changes in seconds instead of minutes.

**Comment by sunnyghai** [comment]
Dave, after doing some testing, it looks like that some changes outside of the ST App (Kasa or physically) do update eventually.  However, it can take anywhere from 20 seconds to several minutes or more.

**Comment by DaveGut** [comment]
See the new code and instructions.  I can not improve the performance of the refresh from an external source.  The only control there is Refresh Rate.  There is still an element of SmartThings problems in some of the phone app updates.

**Comment by DaveGut** [comment]
Closing due to lack of return comments.  Previous post provided an updated driver/app set and the documentation has been updated to explicitly cover updates.
