### ISSUE TITLE
Adding TP link hs100 switch

### ISSUE THREAD

**Issue by tonyt13** [DaveGut/TP-Link-SmartThings#14]
I have a TP link HS110 added and working, and have just got 2 further HS100's. When trying to add, I get an error saving page, and this in the live log:

04:23:04: error physicalgraph.app.exception.UnknownDeviceTypeException: Device type '(Cloud) TP-Link Plug-Switch' in namespace 'davegut' not found. @line 206 (doCall)

Any ideas please?

**Comment by DaveGut** [comment]
You need to update the Smart App and drivers to latest version.  The Plug-Switch device type was split into separate plug and switch to support iconography in the new SmartThings app.  Please respond if this works.

**Comment by tonyt13** [comment]
﻿Cheers Dave – will try when home and let you know

Thanks again for the reply

Tony

**Comment by DaveGut** [comment]
Closing due to lack of return comments.  Provided an updated driver/app set and the documentation has been updated to explicitly cover updates.
