### ISSUE TITLE
New SmartApp From Code Pasting

### ISSUE THREAD

**Issue by psklaver** [DaveGut/TP-Link-SmartThings#17]
Hi - I am receiving an error whenever I try to paste the code for TP-Link Switch.groovy 

Not sure what I am doing wrong. Any advice on getting through this step would be appreciated. Error I am receiving is below:

No signature of method: script_app_metadata_939c3bc5_df35_4507_940f_bbaea1f0300e.metadata() is applicable for argument types: (script_app_metadata_939c3bc5_df35_4507_940f_bbaea1f0300e$_run_closure1) values: [script_app_metadata_939c3bc5_df35_4507_940f_bbaea1f0300e$_run_closure1@50a55dd2] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by DaveGut** [comment]
Only thing I can thing is you are missing some text.  There is also a case (rarer) where the copy process does not copy text properly.

The first two lines should be:

/*
TP-Link Plug and Switch Device Handler, 2018, Version 3

The last line should be:
//end-of-file

**Comment by psklaver** [comment]
solved! thank you!

**Comment by DaveGut** [comment]
Closed via previous message.
