### ISSUE TITLE
Unable to save after entering users info. 

### ISSUE THREAD

**Issue by gdccreations** [DaveGut/TP-Link-SmartThings#19]
So I entered my users info and clicked same and it worked but I got a token error. So I removed the app and reinstalled and now I no longer can save after entering users info. [](
![824e4593-aee6-4628-8558-1b67be748fcb](https://user-images.githubusercontent.com/31079150/53684736-ad51d500-3cd6-11e9-864f-014a6472e0ff.jpeg)

**Comment by DaveGut** [comment]
I need error logs to be able to do anything.  Without those, I have no clue as to what is going on.

(PS - I believe that when the text box pops up, it has a done button.  Make sure you press that and exit the latest field entered.  This may be causing the issue.)

**Comment by DaveGut** [comment]
Test service manager solves problem.  Will be formalized this week.

EDIT.  Finalized test.  Verified by other users with same issue.

**Comment by DaveGut** [comment]
Updated driver completed and verified.
