### ISSUE TITLE
No response in Get or Update Kasa Token screen

### ISSUE THREAD

**Issue by utpatrick** [DaveGut/TP-Link-SmartThings#20]
Tried to enter the Kasa account credentials with the Done button. However, no response is returned when clicked on the Get or Update Kasa Token tab. The scheduled job is shown as below:

1. Go to Select Installation Type -> Kasa Account
2. Type in Kasa Email and Account Password (Password seems to auto fill-in no matter what I typed)
3. Click on Get or Update Kasa Token
4. Loading icon showed but nothing happened, see event pending:

getToken | 2019-04-30 10:30:00 PM EDT |   | PENDING | 0 30 2 ? * WED UTC
-- | -- | -- | -- | --

1:13:01 AM: info Waiting on events...

 - Device: [iphone 8 plus]
 - OS: [iOS 12.1.1]

**Comment by DaveGut** [comment]
Corrected???? 

Typically, it is caused by autofill of the password.  Something I can not control.

I need logs to better address.

**Comment by utpatrick** [comment]
Can you direct me where to get a full log? I only see the getToken pending and no more information, thanks!

**Comment by DaveGut** [comment]
By turning on logging on the IDE.

**Comment by utpatrick** [comment]
Seems like I can't getToken from the kasaAuthenticationPage:

cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:40 PM: trace 4.0.04 kasaAuthenticationPage
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:38 PM: error java.lang.NullPointerException: Cannot get property 'id' on null object @line 507 (getToken)
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:38 PM: trace 4.0.04 getToken lordbruce727@gmail.com
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:38 PM: trace 4.0.04 flowDirector flowType = updateKasaToken
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:38 PM: trace 4.0.04 welcomePage: installType = Kasa Account
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:38 PM: error java.lang.NullPointerException: Cannot get property 'id' on null object @line 507 (getToken)
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:38 PM: trace 4.0.04 getToken lordbruce727@gmail.com
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:38 PM: trace 4.0.04 flowDirector flowType = updateKasaToken
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:38 PM: trace 4.0.04 welcomePage: installType = Kasa Account
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:37 PM: trace 4.0.04 kasaAuthenticationPage
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:37 PM: trace 4.0.04 kasaAuthenticationPage
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:35 PM: trace 4.0.04 kasaAuthenticationPage
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:28 PM: trace 4.0.04 kasaAuthenticationPage
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:24 PM: trace 4.0.04 kasaAuthenticationPage
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:24 PM: trace 4.0.04 kasaAuthenticationPage
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:21 PM: trace 4.0.04 kasaAuthenticationPage
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:05:13 PM: trace 4.0.04 kasaAuthenticationPage
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:04:59 PM: trace 4.0.04 kasaAuthenticationPage
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:04:59 PM: trace 4.0.04 startPage: installType = Kasa Account
f7cdeb48-2b69-4cce-af99-409c1b39dba7  12:04:53 PM: trace 4.0.04 startPage: installType = null
25a8e4b1-9bd6-4388-8815-a595809b629f  12:04:53 PM: trace getPhrases(), state.welcomeIssue = null
25a8e4b1-9bd6-4388-8815-a595809b629f  12:04:45 PM: trace getPhrases(), state.welcomeIssue = null
25a8e4b1-9bd6-4388-8815-a595809b629f  12:04:28 PM: trace getPhrases(), state.welcomeIssue = null

**Comment by utpatrick** [comment]
hey Dave, I think i need to get a smartthing hub installed in order to make this line work:

terminalUUID: "${hub.id}"

i'll update once I get the device in place, thanks!

**Comment by DaveGut** [comment]
Yes.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by DaveGut** [comment]
Unsupported Capability.
