### ISSUE TITLE
Issues with switches not turning off

### ISSUE THREAD

**Issue by sunnyghai** [DaveGut/TP-Link-SmartThings#21]
Dave,

I have numerous WebCoRE pistons that are supposed to turn off a TP-Link switch or plug after a wait delay.  Recently my light switches stopped turning off once WC issues a "turn on" or level  command.  

I started troubleshooting by focusing on just one of the switches.  The Debug log doesn't show the switch ever turning on, even though it physically turns on (both by a piston or through the app).  I called ST support, and they were absolutely no help.  Any suggestions?

Sunny

**Comment by DaveGut** [comment]
SmartThings logging has been unreliable for months.  You can see a list of recent events (on, off, other attribute setting) in the classic app (I do not know about the new app).  On the My Home page select the device.  At the top, select the tab Recently.  This lists all event transitions (i.e., on to off but not on to o).
