### ISSUE TITLE
Manager doesn't see device

### ISSUE THREAD

**Issue by jipis** [DaveGut/TP-Link-SmartThings#23]
- I have an HS-200 switch. It's already on my network.
- I've set up a node server also on the network.
- I've added the SmartThings Manager and set it to "Node Applet" mode. I enter the IP address of the Node.js hub. It confirms correctly and brings me to the Kasa Device Management Page.
- It finds no devices to add.

Now, what I don't get at all is that I can control my switch from the Kasa app, but the IP address assigned to the switch is unreachable on the network. What am I missing here??

**Comment by DaveGut** [comment]
I need logs to understand what and where the error may be occurring.

**Comment by DaveGut** [comment]
Closing issue since.  Insufficient details and no return information from submitter.

**Comment by jipis** [comment]
Sorry, I didn't see the notification that you'd responded a few weeks ago.

Logs would be the problem.... Nothing to log. I can ping the HS200 switch from my Pi. But, if I run `GetDeviceIPs.js`, I end up with an empty list.

Thoughts or suggestions?

**Comment by DaveGut** [comment]
Possibly means your devices are on a different subnet from the device running getDeviceIPs.

I just ran and got the expected results.

**Comment by jipis** [comment]
Ugh, don't I wish. All the same network....
```
GW 192.168.1.1
Pi 192.168.1.201
HS200 192.168.1.119
NM 255.255.255.0
```

**Comment by DaveGut** [comment]
Do you get any display at all when you run the polling??  Just downloaded from GitHub, and I get no errors.

This is a sample of what I get (first device only) on  PX.  You should at least see the first line (always) and the last on a PC.

List of TP-Link Devices with IP, MAC, Alias, and Model
{ '50C7BF199E99':
   { deviceIP: '192.168.0.115',
     deviceModel: 'HS200(US)',
     deviceAlias: 'Bedroom Fan',
     deviceId: '8009999999AF6CEA0C50B6C140BEDF2D17D9999' }
Press any key to continue . . .

**Comment by jipis** [comment]
Yeah, it's my network. Not sure what else to chalk it up to. Or the switch is just wonky. /shrug dunno

My output is just 
```
List of TP-Link Devices with IP, MAC, Alias, and Model
{}
```
on a RaspberryPi running Raspbian.

As a linux admin and software dev, this shouldn't be this hard.

In any case, just going to look into z-wave switches... SMH

Thanks for your help.

**Comment by DaveGut** [comment]
What is your node.js version?  This may have something to do with it (although I would expect an error).

**Comment by jipis** [comment]
node 8.11.1

**Comment by DaveGut** [comment]
I was already on 8.11.3.  It was developed on a 6.x version, so it is not the Node.js version.

If you have a PC with node.js installed, try running it from a browser there (using batch file I included).  In the past, some have had problems if not on the same network (i.e., guest vice standard wifi).   I have never tested; however, these devices are sometimes strange.
