### ISSUE TITLE
HS110 and HS115 energy monitoring capability

### ISSUE THREAD

**Issue by TattsUK** [DaveGut/TP-Link-SmartThings#24]
Hello,
I am working on a project where I will need to simultaneously record the power consumption of some electrical equipment installed at several locations across the UK and this remotely. I need to be able to go back in time and see the power consumption for the last say 7 days with a time resolution of at least one per hour.
I found this repository and am wondering whether it could solve my problem.
Going through the documentation, I can see that the HS110 and HS115 report the current power, today's usage, the 7 day total, the 7 day average, the 30 day total and the 30 day average. Is there any way via Smart Things to get a better data granularity/time resolution? I am new to Smart Things.
Thank you
Kind regards
Nicolas

**Comment by DaveGut** [comment]
**Current Power:**  Currently, the programmed granularity in the driver is 1 minute for current power.  There are ways to capture (send SMS, use IFTTT to log to a spreadsheet, etc) whenever the value changes.  That would give you a time - usage graph with a one minute granularity.  (You will need to check with others for how this is done.  I have never used it, so ....)

**Better current power granularity:**  As far as better granularity for current power - possible, but would require code changes and would be a stress on the system.

**Other parameters:**  For the other parameters, no better is available.  The system collects power by the day and maintains it in the device.  Once you capture power changes, you could integrate this using the spread-sheet to get a total by a period you define.

**Comment by TattsUK** [comment]
Thank you for this. The IFTTT option sounds great. Is this something that can be done with a smart things hub? Would you be able to direct me to a user who has done this before?

**Comment by DaveGut** [comment]
Sorry, I am really limited in this area.  A query on the Smart Things forum would possibly get some results.  There have been several discussions on capturing data and logging to a file.

**Comment by TattsUK** [comment]
Thank you, I will do that
