### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by rchoughton** [DaveGut/TP-Link-SmartThings#3]
I have just installed the device handler and smart app.  I appreciate all the effort and it looks like it overall works great.  I have a few thinks I am running into. Neither seems to be impacting the system from working, but wanted to see if there was a solution to either or something I have not set correctly.
If I loose power to a plug, I do not get any update in SmartThings noting that.  In the log for each device this has happened to I get the error "
f1573196-3037-4a5d-8606-04ccd2baa7d5  5:16:50 AM: error groovy.lang.MissingMethodException: No signature of method: physicalgraph.device.DeviceTypeExecutorBase$_closure5.doCall() is applicable for argument types: (java.lang.String, java.lang.reflect.UndeclaredThrowableException) values: [Sending Command Exception: , java.lang.reflect.UndeclaredThrowableException]
Possible solutions: doCall(), doCall(java.lang.Object), call(), call([Ljava.lang.Object;), call(java.lang.Object), findAll() @line 193 (sendCmdtoServer)"
After 5 minutes I do get an update that it is unavailable in SmartThings and this is in the log. " Interface Error.	See SmartApp and Device error message." This may be how it is designed, but wanted to check because of the error message.

Also, I seems to be having difficulty updating preferences. When update the preference in the SmartApp and save, I get this error.
" error java.lang.NullPointerException: Cannot get property 'value' on null object @line 903 (doCall)"
Any suggestions?
Thanks.

**Comment by DaveGut** [comment]
First issue is fixed in updated Device Handlers now posted on GitHub.
Second error is on userSelectedNotification option.  This function is not working (sends an SMS message when almost anything happens).  I don't plan on fixing this feature - just too much.  Will delete in future revision of the app.

**Comment by DaveGut** [comment]
Issue closed with the above items.
