### ISSUE TITLE
Unable to uninstall the SmartApp

### ISSUE THREAD

**Issue by Frankwin** [DaveGut/TP-Link-SmartThings#4]
I'm trying to uninstall the SmartThings SmartApp on my phone, but it doesn't work. I'm having issues with my SmartThings App no longer being able to add any new devices ever since I installed the SmartThings SmartApp so that's why I'm tyring to uninstall it. 

I did the Live Logging and this is what the Log shows:

66c3f70a-b90a-4f5e-bd18-d98f970d717b  6:40:47 PM: error org.springframework.dao.DataAccessResourceFailureException: could not execute query; nested exception is org.hibernate.exception.JDBCConnectionException: could not execute query
66c3f70a-b90a-4f5e-bd18-d98f970d717b  6:40:32 PM: error uninstManagerApp Exception: org.springframework.dao.DataAccessResourceFailureException: could not delete: [physicalgraph.app.InstalledSmartAppData#4ca00ffd-011a-41f6-b0e7-390864e0db4f]; nested exception is org.hibernate.exception.JDBCConnectionException: could not delete: [physicalgraph.app.InstalledSmartAppData#4ca00ffd-011a-41f6-b0e7-390864e0db4f] @line 1269 (settingRemove)
66c3f70a-b90a-4f5e-bd18-d98f970d717b  6:40:04 PM: trace settingRemove(userName)...
66c3f70a-b90a-4f5e-bd18-d98f970d717b  6:40:28 PM: trace settingRemove(userSelectedOptionTwo)...
66c3f70a-b90a-4f5e-bd18-d98f970d717b  6:40:28 PM: trace settingRemove(userSelectedOptionThree)...
66c3f70a-b90a-4f5e-bd18-d98f970d717b  6:40:28 PM: trace settingRemove(userSelectedDevicesToUpdate)...
66c3f70a-b90a-4f5e-bd18-d98f970d717b  6:40:28 PM: trace settingRemove(userSelectedDevicesAdd)...
66c3f70a-b90a-4f5e-bd18-d98f970d717b  6:40:28 PM: trace settingRemove(userSelectedDevicesRemove)...
66c3f70a-b90a-4f5e-bd18-d98f970d717b  6:40:28 PM: trace settingUpdate(userSelectedReload, false, bool)...

**Comment by DaveGut** [comment]
Try first removing all of the devices.  If that fails, try updating to the "Lite" version of the Smart App (replace code in file in SmartThings.  That uses a remove button on the first page and avoids the code above.  I really do not have a clue and have never encountered (10 plus installs and deletes.  Let me know.

**Comment by DaveGut** [comment]
No update in 6 days.  Close.
