### ISSUE TITLE
HS210 Support?

### ISSUE THREAD

**Issue by desiwalle** [DaveGut/TP-Link-SmartThings#6]
Wondering if the HS210 is supported? Tryng to setup automation to switch on the HS210 via a Motion Sensor trigger, but success is inconsistent. There are no issues switching on an HS200 using the same Smart Lighting automation routine and motion sensor. When the automation does not work, the switch turns on and then off within 1 second.

**Comment by dmkzzz** [comment]
Yes, I am attempting the same thing

**Comment by DaveGut** [comment]
I do not own a HS-210.  Would love to fix this issue, but I need data.

a.  does the HS-210 have two IP addresses?

I will consider a special device handler to log data for the HS-210 devices (it will essentially replace the existing, but will include enhanced logging so I can see what is going on.).  Interested?????

Dave

**Comment by desiwalle** [comment]
>           I do not own a HS-210.  Would love to fix this issue, but I need data.
> a.  does the HS-210 have two IP addresses?
> I will consider a special device handler to log data for the HS-210 devices (it will essentially replace the existing, but will include enhanced logging so I can see what is going on.).  Interested?????
> Dave

@DaveGut , Yes, thanks, I am interested. The HS-210 "kit" is a 2-switch system. Each switch has it's own IP address.

**Comment by DaveGut** [comment]
I have loaded a test device handler in the folder "Test Code".  It just logs the message being sent and the received response - so I can correlate both actions and (more importantly) the data structure of the returned data).

Instructions:
a.  Create a new Device Handler from this code.  Save and publish.
b.  Go to the My Devices tab and select your HS210 (or two if there are two devices loaded).
c.  Select Edit at the bottom and change the Type using the pull-down to "Test Switch"
d.  Open live logging.
e.  Execute a On command on your device(s) followed 10 seconds later by a Refresh command.
f.  Select the tab for each device in logging.  Copy log and paste to a text file.
g.  Add the text file as an attachment in a return message.
h.  Go back to the My Devices tab and return your type to the original.
i.  (Nice to have, but not critical) In the phone app, go to the Device Uninstall page.  Capture the list of devices in the pull down (screen capture) and paste in message.

Dave

**Comment by DaveGut** [comment]
One other item (from a GitHub search):

"I just installed some of the HS210 kits. And came up with this solution.
I figured out which of the two was the main switch and which was the dummy in the Home app.
These lights are for my Front Hall, so I renamed the one that worked FH Live and the other FH Dummy then grouped them as simply Front Hall.
Now I just have the one device listed and all the commands work fine calling it Front Hall."

A quick work-around.  Do the above and delete the dummy.  However, maybe I can figure who the slave is with the data you provide.  I think that if you command the slave, the master does not follow!

**Comment by desiwalle** [comment]
@DaveGut , Thanks for the quick turnaround. I'm away from the house for 2-3 days. If it's OK with you, I'll test it upon my return.

**Comment by sunnyghai** [comment]
I have a number of HS210 Switches working using the current device handler. It’s not necessary to use the kit as they have described (on a single circuit). I have been able to split the two switches to use on two separate 3-way circuits and they work fine. Check the reviews on Amazon for additional info. 

https://www.amazon.com/gp/customer-reviews/R1GHG6NKHTRWSD/ref=cm_cr_arp_d_viewpnt?ie=UTF8&ASIN=B07724HNTX#R1GHG6NKHTRWSD

**Comment by desiwalle** [comment]
> @DaveGut , Thanks for the quick turnaround. I'm away from the house for 2-3 days. If it's OK with you, I'll test it upon my return.

Sorry about the delayed response. You can close this issue. It turns out I had a bad Hub. Upon replacing the hub, the HS210 is responding just fine. Either that, or the gremlins found a way out :-) #
