### ISSUE TITLE
HS105 - Unable to setup in TP-Link-SmartThings

### ISSUE THREAD

**Issue by dashmartin** [DaveGut/TP-Link-SmartThings#8]
I'm able to get the SmartThings Manager added to the SmartApps and the TP-Link SmartPlug added to Device Handler in the SmartThings IDE site. I'm able to see the manager in SmartThings Classic. I tap on that, choose Kasa, enter my Kasa credentials and when I tap on Install devices to continue, I get a page that says "Something's Wrong. We can't load your screen right now" with a Retry button. I assume the server the app uses to authenticate the Kasa credentials may be down, but the Kasa app is working fine.

**Comment by DaveGut** [comment]
Turn on live logging and capture any error message when encountering.  That will give a clue to the error.  Checklist:
a.  Did you select My Location and then your hub before installing the DH and Service Manager (SmartApp) code.
b.  Are you sure you loaded the correct app.  It must be the "TP-Link Plug.groovy" file.

**Comment by dashmartin** [comment]
9a36b060-78b7-46e7-9ad5-133a80a67390 8:05:13 PM: error java.lang.NullPointerException: Cannot get property 'id' on null object @line 651 (getToken)

9a36b060-78b7-46e7-9ad5-133a80a67390 8:05:13 PM: error java.lang.NullPointerException: Cannot get property 'id' on null object @line 651 (getToken)

9a36b060-78b7-46e7-9ad5-133a80a67390 8:05:13 PM: error java.lang.NullPointerException: Cannot get property 'id' on null object @line 651 (getToken)

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:46 PM: trace settingRemove(userPassword)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:46 PM: trace settingRemove(userName)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:46 PM: trace settingRemove(userSelectedOptionTwo)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:46 PM: trace settingRemove(userSelectedOptionThree)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:46 PM: trace settingRemove(userSelectedDevicesToUpdate)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:46 PM: trace settingRemove(userSelectedDevicesAdd)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:46 PM: trace settingRemove(userSelectedDevicesRemove)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:46 PM: trace settingUpdate(userSelectedReload, false, bool)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:43 PM: trace settingRemove(userPassword)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:43 PM: trace settingRemove(userName)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:43 PM: trace settingRemove(userSelectedOptionTwo)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:43 PM: trace settingRemove(userSelectedOptionThree)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:43 PM: trace settingRemove(userSelectedDevicesToUpdate)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:43 PM: trace settingRemove(userSelectedDevicesAdd)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:43 PM: trace settingRemove(userSelectedDevicesRemove)...

9a36b060-78b7-46e7-9ad5-133a80a67390 8:04:43 PM: trace settingUpdate(userSelectedReload, false, bool)...

eb27dd37-4d67-4682-8b52-044065b583af 8:04:32 PM: trace getPhrases(), state.welcomeIssue = null

b2f5081d-bd92-4ec3-b6be-b963bb94002d 8:04:30 PM: info SHM getInitialData 0.028 (00) incidents:00, locationId:b277c63d-cfbb-426b-9eb8-88490352af38

b2f5081d-bd92-4ec3-b6be-b963bb94002d 8:04:30 PM: debug summaryData: [[icon:indicator-dot-gray, iconColor:#878787, value:Unconfigured]] - [[icon:indicator-dot-gray, iconColor:#878787, value:Unconfigured]]

 

It shows up in my location when I start the setup process. It goes away when I exit the SmartThings Classic app.

 

 



 

I tried the SmartPlug file instead of Switch…but I get the same error no matter which.

 

I don’t own a hub. Is it necessary? Our SmartThings enabled Samsung TV doesn’t require one.

 

-Dash

**Comment by DaveGut** [comment]
It is not recognizing the SmartThings Hub you are connected to.  See 2nd post in this string.  You MUST have a hub and you MUST select this hub prior to loading the DHs or SmartApps into the IDE.  On the next update, I will mask this error and replace with an explicit message reflecting the above,

**Comment by dashmartin** [comment]
Got it. So to use this without a hub, I have to go the Node route and set
that up on my PC then?

**Comment by DaveGut** [comment]
Sadly, no.  This series requires a SmartThings hub to operate.  There is no work-around since the SmartThings hub provides the processing infrastructure.

**Comment by DaveGut** [comment]
Issue is related to installation without a SmartThings hub which is not supported
